# THIS TEST SCRIPT WAS GENERATED BY AI
import os
import gzip
import time
import random
import requests
from pathlib import Path

def generate_test_dataset(chromosome_id, start_pos, length=500, mutation_rate=0.02, output_dir="data"):
    """
    Downloads reference chromosome, extracts a target segment,
    introduces SNPs, Insertions, and Deletions to test the alignment engine,
    saves the result, and IMMEDIATELY deletes the heavy reference file.
    """
    chrom_clean = str(chromosome_id).lower().replace("chr", "").strip()
    url = f"https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/001/405/GCF_000001405.40_GRCh38.p14/GCF_000001405.40_GRCh38.p14_assembly_structure/Primary_Assembly/assembled_chromosomes/FASTA/chr{chrom_clean}.fna.gz"

    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)
    
    temp_dir = output_path / "temp"
    temp_dir.mkdir(parents=True, exist_ok=True)

    temp_gzip_path = temp_dir / f"temp_ref_chr{chrom_clean}.fasta.gz"
    patient_file_path = output_path / f"patient_chr{chrom_clean}_mutated.fasta.gz"

    # 1. Скачиваем временный тяжелый файл
    print(f"Downloading reference chromosome {chrom_clean} from NCBI...")
    try:
        response = requests.get(url, stream=True, timeout=30)
        response.raise_for_status()
        with open(temp_gzip_path, "wb") as f:
            for chunk in response.iter_content(chunk_size=65536):
                if chunk:
                    f.write(chunk)
        print("Download complete.")
    except Exception as e:
        print(f"Failed to download reference chromosome: {e}")
        return None

    # 2. Вытаскиваем нужный кусок (берём с запасом x2 для компенсации инделов)
    print(f"Extracting segment starting from position {start_pos}...")
    ref_buffer = []
    bytes_read = 0
    target_started = False

    with gzip.open(temp_gzip_path, "rt") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith(">"): 
                continue
            
            line_len = len(line)
            if not target_started and bytes_read + line_len >= start_pos:
                target_started = True
                offset = start_pos - bytes_read - 1
                ref_buffer.append(line[offset:])
            elif target_started: 
                ref_buffer.append(line)
                
            bytes_read += line_len
            if target_started and sum(len(s) for s in ref_buffer) >= length * 2:
                break

    reference_sequence = "".join(ref_buffer)[:length * 2].upper()

    # 3. Генерируем полноценные мутации (SNP, Insertion, Deletion)
    print(f"Simulating mutations with a rate of {mutation_rate * 100}%...")
    bases = ['A', 'C', 'T', 'G']
    patient_sequence = []
    stats = {"SNP": 0, "Deletion": 0, "Insertion": 0}

    random.seed(int(os.getpid() + start_pos + time.time()))

    ref_idx = 0
    while len(patient_sequence) < length and ref_idx < len(reference_sequence):
        ref_base = reference_sequence[ref_idx]
        
        if random.random() < mutation_rate:
            mut_type = random.choice(["SNP", "Deletion", "Insertion"])
            
            if mut_type == "SNP":
                possible_mutations = [b for b in bases if b != ref_base]
                patient_sequence.append(random.choice(possible_mutations))
                stats["SNP"] += 1
                ref_idx += 1
            elif mut_type == "Deletion":
                stats["Deletion"] += 1
                ref_idx += 1  # Просто пропускаем букву референса
            elif mut_type == "Insertion":
                patient_sequence.append(ref_base)
                patient_sequence.append(random.choice(bases))  # Вставляем лишнюю букву
                stats["Insertion"] += 1
                ref_idx += 1
        else:
            patient_sequence.append(ref_base)
            ref_idx += 1
            
    final_patient_string = "".join(patient_sequence)[:length]

    # 4. Сохраняем результат пациента
    with gzip.open(patient_file_path, "wt") as f_out:
        f_out.write(f">patient_chr{chrom_clean}_simulated position={start_pos} length={length}\n")
        f_out.write(final_patient_string + "\n")
        
    # 5. ТРЭШ-КОНТРОЛЬ: Немедленно удаляем гигабайты референса
    if temp_gzip_path.exists(): 
        os.remove(temp_gzip_path)
    if temp_dir.exists() and not os.listdir(temp_dir):
        os.rmdir(temp_dir)
        
    print("\n" + "="*50)
    print(f"SUCCESS: Test dataset generation finished. Disk space cleared.")
    print(f"Target Compressed File: {patient_file_path}")
    print(f"Total Length: {len(final_patient_string)} bases")
    print(f"Injected: {stats['SNP']} SNPs, {stats['Deletion']} Del, {stats['Insertion']} Ins")
    print("="*50)

    return patient_file_path

if __name__ == "__main__":
    generate_test_dataset(chromosome_id="21", start_pos=15100400, length=1000, mutation_rate=0.03)